name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9" ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy wemake-python-styleguide flake8-html

    - name: Create report directories
      run: |
        mkdir -p reports/mypy_reports/action_api
        mkdir -p reports/styleguide_reports/action_api

    - name: PR review with wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}

    - name: Run mypy
      run: |
        mypy ugc_api --ignore-missing-imports --html-report reports/mypy_reports/ugc_api
        mypy action_api --ignore-missing-imports --html-report reports/mypy_reports/action_api
        mypy etl_ugc --ignore-missing-imports --html-report reports/mypy_reports/etl_ugc

    - name: Run flake8/styleguide
      run: |
        flake8 ugc_api --config=setup.cfg --exit-zero --format=html --htmldir=reports/styleguide_reports/ugc_api
        flake8 action_api --config=setup.cfg --exit-zero --format=html --htmldir=reports/styleguide_reports/action_api
        flake8 etl_ugc --config=setup.cfg --exit-zero --format=html --htmldir=reports/styleguide_reports/etl_ugc

  notification:
  needs: build
  if: always()
  runs-on: ubuntu-latest
  steps:
    - name: send telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          New Pull Request in ${{ github.repository }}: ${{ github.event.pull_request.title }}
          Author: ${{ github.actor }}
          Commit message: ${{ github.event.commits[0].message }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          Pipeline status: ${{ needs.build.result }}
