version: '3'

services:
  action_api:
    build: ./ugc-action_api
    container_name: action_api
    entrypoint: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port $ACTION_PORT"
    expose:
      - ${ACTION_PORT}
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - ugc
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
      - "8000:80"

networks:
  default:
    name: movies_networks
    external: true