version: '3'

services:
  action:
    build: ./action_api
    container_name: action
    entrypoint: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port $ACTION_PORT"
    expose:
      - ${ACTION_PORT}
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - action
      - logstash
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - /tmp/logs/nginx/:/var/log/nginx/
    ports:
      - "80:80"
      - "8000:80"
    links:
      - logstash 

  logstash:
    image: logstash:7.14.2
    container_name: logstash
    depends_on:
      - elasticsearchelk
    env_file:
      - ./.env
    ports:
      - "5044:5044/udp"
    volumes:
      - ./deploy/logstash/logstash.conf:/config/logstash.conf:ro
      - /tmp/logs/nginx/:/var/log/nginx/:ro
    command: logstash -f /config/logstash.conf

  elasticsearchelk:
    image: elasticsearch:7.14.2
    container_name: elasticsearchelk
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - 9200:9200
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data
  
  kibana:
    image: kibana:7.14.2
    container_name: kibana
    ports:
      - "5601:5601"
    env_file:
      - ./.env
    depends_on:
      - elasticsearchelk

networks:
  default:
    name: movies_networks  
    external: true