name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        script: |
          export PROJECT_NAME=${{ secrets.PROJECT_NAME }}
          export ACTION_HOST=${{ secrets.ACTION_HOST }}
          export ACTION_PORT=${{ secrets.ACTION_PORT }}
          export MONGODB_URL=${{ secrets.MONGODB_URL }}
          export MONGODB_LOCAL_URL=${{ secrets.MONGODB_LOCAL_URL }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml types-requests mypy flake8 wemake-python-styleguide flake8-html
        pip install -r action_api/requirements.txt

    - name: Create report directories
      run: |
        mkdir -p reports/mypy_reports/action_api
        mkdir -p reports/styleguide_reports/action_api

    - name: Run mypy
      run: |
        MYPYPATH=action_api/src mypy action_api --ignore-missing-imports --explicit-package-bases --html-report reports/mypy_reports/action_api

    - name: Run flake8/styleguide
      run: |
        flake8 action_api --config=setup.cfg --exit-zero --format=html --htmldir=reports/styleguide_reports/action_api
        
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: reports/

    - name: Run tests
      run: |
        cd tests/
        touch .env
        echo PROJECT_NAME=${{ secrets.PROJECT_NAME }} > .env
        echo ACTION_HOST=${{ secrets.ACTION_HOST }} > .env
        echo ACTION_PORT=${{ secrets.ACTION_PORT }} > .env
        echo MONGODB_URL=${{ secrets.MONGODB_URL }} > .env
        echo MONGODB_LOCAL_URL=${{ secrets.MONGODB_LOCAL_URL }} > .env
        docker-compose up -d
        make
        pip install -r requirements.txt
        pytest -v -s -p no:warnings

  message:

    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build
    steps:
    - name: send telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          New Pull Request in ${{ github.repository }}: ${{ github.event.pull_request.title }}
          Author: ${{ github.actor }}
          Commit message: ${{ github.event.commits[0].message }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          Pipeline status: ${{ needs.build.result }}
