name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml types-requests mypy flake8 wemake-python-styleguide flake8-html
        pip install -r action_api/requirements.txt

    - name: Create report directories
      run: |
        mkdir -p reports/mypy_reports/action_api
        mkdir -p reports/styleguide_reports/action_api

    - name: Run mypy
      run: |
        mypy action_api --html-report reports/mypy_reports/action_api

    - name: Run flake8/styleguide
      run: |
        flake8 action_api --config=setup.cfg --exit-zero --format=html --htmldir=reports/styleguide_reports/action_api
        
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: reports/

  message:

    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build
    steps:
    - name: send telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          New Pull Request in ${{ github.repository }}: ${{ github.event.pull_request.title }}
          Author: ${{ github.actor }}
          Commit message: ${{ github.event.commits[0].message }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          Pipeline status: ${{ needs.build.result }}
